config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :recipes do
		resources :ingredients
		resources :directions
	end

	root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :ingredients
	has_many :directions

	accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

	accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true

	validates :title, :description, :image, presence: true

	has_attached_file :image, styles: { medium: "400x400#" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController

	before_action :set_recipe 

	def create
		
		@direction = @recipe.directions.create(direction_params)

		redirect_to @recipe
	end

	def destroy
		@direction = @recipe.directions.find(params[:id])

		if @direction.destroy
			flash[:success] = "Ingredient Deleted"
		else
			flash[:error] = "Ingredient couldn't be deleted."
		end

		redirect_to @recipe
	end

	private

		def set_recipe
			@recipe = Recipe.find(params[:recipe_id])
		end

		def direction_params
			params[:direction].permit(:step)
		end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

	before_action :set_recipe 

	def create
		
		@ingredient = @recipe.ingredients.create(ingredient_params)

		redirect_to @recipe
	end

	def destroy
		@ingredient = @recipe.ingredients.find(params[:id])

		if @ingredient.destroy
			flash[:success] = "Ingredient Deleted"
		else
			flash[:error] = "Ingredient couldn't be deleted."
		end

		redirect_to @recipe
	end

	private

		def set_recipe
			@recipe = Recipe.find(params[:recipe_id])
		end

		def ingredient_params
			params[:ingredient].permit(:name)
		end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]

	def index
		@recipe = Recipe.all.order("created_at DESC")
	end

	def show
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)

		if @recipe.save
			params[:ingredients].split("\n").each do |ingredient|
				@recipe.ingredients.create(name: ingredient)
			end

			redirect_to @recipe, notice: "Successfully created new recipe!"
		else
			render "new"
		end
	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else 
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Successfully deleted recipe"
	end

	private

		def recipe_params
			params.require(:recipe).permit(:title, :description, :image)
		end

		def find_recipe
			@recipe = Recipe.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/directions/_direction.html.erb
<div class="direction__name"> <%= direction.step %> </p>

	<%= link_to recipe_direction_path(@recipe, direction.id), method: :delete, data: {} do %> 
    	<i class="fa fa-times" aria-hidden="true"></i>
	<%end%>

</div>

app/views/directions/_form.html.erb
<%= form_for( [@recipe, @recipe.directions.build] ) do |f| %>
	<%= f.text_field :step, placeholder: "New Step" %>
	<%= f.submit %>
<% end %>

app/views/ingredients/_form.html.erb
<%= form_for( [@recipe, @recipe.ingredients.build] ) do |f| %>
	<%= f.text_field :name, placeholder: "New Ingredient" %>
	<%= f.submit %>
<% end %>

app/views/ingredients/_ingredient.html.erb
<div class="ingredient__name"> <%= ingredient.name %> 

<%= link_to recipe_ingredient_path(@recipe, ingredient.id), method: :delete, data: {} do %> 
    	<i class="fa fa-times" aria-hidden="true"></i>
	<%end%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar"> 
  		<container class="navbar__logo"> 
        <%= link_to root_path do %> 
          <i class="fa fa-cutlery" aria-hidden="true"></i>
<i class="fa fa-archive" aria-hidden="true"></i>
        <%end%>

      </container>
  		
      <container class="navbar__links">
  			<span class="navbar__link"><%= link_to "New Recipe", new_recipe_path %></span>
  			<span class="navbar__link"><%= link_to "Sign Out", root_path %></span>
  		</container>

    </nav>

    <%= yield %>

  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
 
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recipe.errors.count, "error") %> prohibited
        this recipe from being saved:
      </h2>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form__recipe">
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
   
    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description, :id => "message_area" %>
    </p>

    <p>
      <%= f.label :image %><br>
       <%= f.file_field :image %>
    </p>

      
    <p>
      <%= f.submit %>
    </p>
  </div>
 
<% end %>

app/views/recipes/edit.html.erb
<div class="edit-container">

	<h1>Edit Recipe</h1>

	<%= render 'form' %>

</div>

app/views/recipes/index.html.erb
<div class="grid">

	<% @recipe.each do |recipe| %>
		<div class="grid__container">
			<div class="grid__image">
			<%= link_to image_tag(recipe.image.url(:medium)), recipe %>  
			</div>
			<h2 class="grid__text"><%= link_to recipe.title, recipe %>  </h2>
		</div>
	<% end %>

</div>

app/views/recipes/new.html.erb
<div class="new">

<h1>New Recipe</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', root_path %>

</div>

app/views/recipes/show.html.erb
<div class="show-container">

	<div class="recipe-container">
		<div class="recipe-container__image"> 
			<%= image_tag @recipe.image.url(:medium) %> 
		</div>
		
		<div class="recipe-container__text">
			<p class="recipe-container__title">
			  <strong>Title:</strong>
			  <%= @recipe.title %>
			</p>
			 
			<p class="recipe-container__description" >
			  <strong>Description:</strong>
			  <%= @recipe.description %>
			</p>

			<div class="recipe-container__links">
				<%= link_to 'Back', root_path , class: "recipe-container__link" %>
				<%= link_to 'Edit', edit_recipe_path , class: "recipe-container__link" %>
				<%= link_to 'Delete', recipe_path, method: :delete, data: {confirm: "Are you sure?"} , class: "recipe-container__link" %>
			</div>

		</div>

	</div>
	<br>
	
	<div class="ingredients-container">
		<%= render @recipe.ingredients %>
		<div>
			<%= render "ingredients/form" %>
		</div>
	</div>

	

	<div class="directions-container">
		<%= render @recipe.directions %>
		<div>
			<%= render "directions/form" %>
		</div>
	</div>


</div>